# Generated by Django 5.0.7 on 2024-08-21 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JoinUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=10)),
                ('reg_no', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=15)),
                ('dob', models.DateField()),
                ('course', models.CharField(max_length=255)),
                ('section', models.CharField(max_length=10)),
                ('personality', models.CharField(max_length=15)),
                ('good_at', models.CharField(max_length=255)),
                ('want_to_learn', models.CharField(max_length=255)),
                ('experience', models.TextField(blank=True, null=True)),
                ('year', models.CharField(max_length=5)),
                ('location', models.CharField(max_length=20)),
                ('referred_by', models.CharField(max_length=255)),
                ('confirmation_sent', models.BooleanField(default=False)),
            ],
        ),
    ]
