# Generated by Django 5.0.7 on 2024-08-21 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('join_us', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='joinus',
            old_name='good_at',
            new_name='domains',
        ),
        migrations.RemoveField(
            model_name='joinus',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='joinus',
            name='want_to_learn',
        ),
    ]
