# Generated by Django 5.0.7 on 2024-08-21 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('join_us', '0002_rename_good_at_joinus_domains_remove_joinus_dob_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='joinus',
            old_name='domains',
            new_name='interested_domain',
        ),
    ]
