# Generated by Django 5.0.7 on 2024-08-21 17:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_us', '0003_rename_domains_joinus_interested_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='joinus',
            name='submitted_at',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
