# Generated by Django 5.0.7 on 2024-10-19 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join_us', '0004_joinus_submitted_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joinus',
            name='submitted_at',
        ),
        migrations.AlterField(
            model_name='joinus',
            name='course',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='joinus',
            name='experience',
            field=models.TextField(blank=True, default=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='joinus',
            name='interested_domain',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='joinus',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='joinus',
            name='personality',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='joinus',
            name='referred_by',
            field=models.CharField(max_length=100),
        ),
    ]
