# Generated by Django 5.0.7 on 2024-12-20 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('join_us', '0005_remove_joinus_submitted_at_alter_joinus_course_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JoinUs',
        ),
    ]
